# Generated by Django 3.1.4 on 2021-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201201_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='exiftool_media_info',
            field=models.TextField(blank=True, help_text='extracted media metadata', verbose_name='Exiftool meta data'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_info',
            field=models.TextField(blank=True, help_text='extracted media metadata', verbose_name='FFprobe meta data'),
        ),
    ]
