# Generated by Django 3.1.4 on 2021-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210419_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='recorded_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date/Time Recorded'),
        ),
        migrations.AddField(
            model_name='media',
            name='recorded_location_gpscoordinates',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='GPS Coordinates'),
        ),
        migrations.AlterField(
            model_name='media',
            name='add_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date/Time Published'),
        ),
        migrations.AlterField(
            model_name='media',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Edited'),
        ),
    ]
