# Generated by Django 3.1.4 on 2021-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_tag_plural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_tag',
            field=models.ManyToManyField(blank=True, related_name='subtags', to='files.Tag'),
        ),
    ]
