# Generated by Django 3.1.4 on 2021-04-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210420_0953'),
        ('files', '0006_auto_20210422_2016'),
    ]

    operations = [
    ]
